version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: pwd
      - run: ls -la
      - run: echo "A first hello"
      - run: mkdir -p my_workspace
      - run: echo "Super testito :)" > my_workspace/testito
      - persist_to_workspace:
          root: my_workspace
          paths:
            - testito
  build2:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Ha a second hello ;)"
      - attach_workspace:
          at: my_workspace

      - run: |
          if [[ $(cat my_workspace/testito) == "Super testito :)" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi
workflows:
  version: 2
  one_and_two:
    jobs:
      - build
      - build2:
          requires:
            - build
